name:                onebrc
version:             0.1.0.0
github:              "githubuser/onebr"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/onebr#readme>

dependencies:
- base >= 4.7 && < 5
- primitive
- bytestring
- containers
- async
- unix
- vector
- mmap
- hashable

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -funbox-strict-fields
- -XLambdaCase
- -XMultiWayIf
- -msse4
- -O2
- -optc-O2
- -optl-s
- -fllvm
# - -keep-llvm-file
# - -keep-s-file

library:
  source-dirs: src

executables:
  onebrc-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - onebrc

  mini-url-bench:
    main:                OneBrcBench.hs
    source-dirs:         bench
    dependencies:
    - onebrc
    - criterion
    - criterion-measurement
    - hourglass

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N    

tests:
  onebr-test:
    main:                Spec.hs
    source-dirs:         spec
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - onebrc
    - hspec

